vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        profile_photos:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
